// This file is auto-generated by @hey-api/openapi-ts

export const $Body_process_video_file_v1_process_video_file_post = {
  properties: {
    file: {
      type: 'string',
      format: 'binary',
      title: 'File'
    },
    description: {
      type: 'string',
      title: 'Description'
    },
    title: {
      type: 'string',
      title: 'Title'
    }
  },
  type: 'object',
  required: ['file', 'description', 'title'],
  title: 'Body_process_video_file_v1_process_video_file_post'
} as const;

export const $HTTPValidationError = {
  properties: {
    detail: {
      items: {
        '$ref': '#/components/schemas/ValidationError'
      },
      type: 'array',
      title: 'Detail'
    }
  },
  type: 'object',
  title: 'HTTPValidationError'
} as const;

export const $TaskOutput = {
  properties: {
    video_id: {
      type: 'integer',
      title: 'Video Id'
    }
  },
  type: 'object',
  required: ['video_id'],
  title: 'TaskOutput'
} as const;

export const $ValidationError = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string'
          },
          {
            type: 'integer'
          }
        ]
      },
      type: 'array',
      title: 'Location'
    },
    msg: {
      type: 'string',
      title: 'Message'
    },
    type: {
      type: 'string',
      title: 'Error Type'
    }
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError'
} as const;

export const $VideoRepr = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id'
    },
    status: {
      type: 'string',
      title: 'Status'
    },
    title: {
      type: 'string',
      title: 'Title'
    },
    description: {
      anyOf: [
        {
          type: 'string'
        },
        {
          type: 'null'
        }
      ],
      title: 'Description'
    },
    url: {
      anyOf: [
        {
          type: 'string'
        },
        {
          type: 'null'
        }
      ],
      title: 'Url'
    },
    file_path: {
      anyOf: [
        {
          type: 'string'
        },
        {
          type: 'null'
        }
      ],
      title: 'File Path'
    },
    tags: {
      anyOf: [
        {
          type: 'string'
        },
        {
          type: 'null'
        }
      ],
      title: 'Tags'
    },
    video_path: {
      anyOf: [
        {
          type: 'string'
        },
        {
          type: 'null'
        }
      ],
      title: 'Video Path'
    },
    text: {
      anyOf: [
        {
          type: 'string'
        },
        {
          type: 'null'
        }
      ],
      title: 'Text'
    },
    audio_path: {
      anyOf: [
        {
          type: 'string'
        },
        {
          type: 'null'
        }
      ],
      title: 'Audio Path'
    }
  },
  type: 'object',
  required: ['id', 'status', 'title', 'description', 'url', 'file_path', 'tags', 'video_path', 'text', 'audio_path'],
  title: 'VideoRepr'
} as const;

export const $VideoUrlInput = {
  properties: {
    video_url: {
      type: 'string',
      maxLength: 2083,
      minLength: 1,
      format: 'uri',
      title: 'Video Url'
    }
  },
  type: 'object',
  required: ['video_url'],
  title: 'VideoUrlInput'
} as const;