// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ProcessVideoUrlV1ProcessVideoUrlPostData, ProcessVideoUrlV1ProcessVideoUrlPostResponse, ProcessVideoFileV1ProcessVideoFilePostData, ProcessVideoFileV1ProcessVideoFilePostResponse, ListVideosV1ListVideosGetResponse, HealthHealthGetResponse } from './types.gen';

export class InferenceEndpointsService {
    /**
     * Process Video Url
     * Обрабатывает видео по URL
     * @param data The data for the request.
     * @param data.requestBody
     * @returns TaskOutput Successful Response
     * @throws ApiError
     */
    public static processVideoUrlV1ProcessVideoUrlPost(data: ProcessVideoUrlV1ProcessVideoUrlPostData): CancelablePromise<ProcessVideoUrlV1ProcessVideoUrlPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/v1/process_video_url',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Process Video File
     * Обрабатывает загруженное видео
     * @param data The data for the request.
     * @param data.formData
     * @returns TaskOutput Successful Response
     * @throws ApiError
     */
    public static processVideoFileV1ProcessVideoFilePost(data: ProcessVideoFileV1ProcessVideoFilePostData): CancelablePromise<ProcessVideoFileV1ProcessVideoFilePostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/v1/process_video_file',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class VideoManagementService {
    /**
     * List Videos
     * Получить список всех видео
     * @returns VideoInfo Successful Response
     * @throws ApiError
     */
    public static listVideosV1ListVideosGet(): CancelablePromise<ListVideosV1ListVideosGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/v1/list_videos'
        });
    }
    
}

export class SystemProbsService {
    /**
     * Health
     * @returns number Successful Response
     * @throws ApiError
     */
    public static healthHealthGet(): CancelablePromise<HealthHealthGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health'
        });
    }
    
}