// This file is auto-generated by @hey-api/openapi-ts

export type Body_process_video_file_v1_process_video_file_post = {
    file: (Blob | File);
    description: string;
    title: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type TaskOutput = {
    task_id: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type VideoInfo = {
    id: number;
    file_path: string;
    status: string;
    progress: number;
    result: string;
    created_at: string;
    updated_at: string;
};

export type VideoUrlInput = {
    video_url: string;
};

export type ProcessVideoUrlV1ProcessVideoUrlPostData = {
    requestBody: VideoUrlInput;
};

export type ProcessVideoUrlV1ProcessVideoUrlPostResponse = TaskOutput;

export type ProcessVideoFileV1ProcessVideoFilePostData = {
    formData: Body_process_video_file_v1_process_video_file_post;
};

export type ProcessVideoFileV1ProcessVideoFilePostResponse = TaskOutput;

export type ListVideosV1ListVideosGetResponse = Array<VideoInfo>;

export type HealthHealthGetResponse = number;

export type $OpenApiTs = {
    '/v1/process_video_url': {
        post: {
            req: ProcessVideoUrlV1ProcessVideoUrlPostData;
            res: {
                /**
                 * Successful Response
                 */
                202: TaskOutput;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/v1/process_video_file': {
        post: {
            req: ProcessVideoFileV1ProcessVideoFilePostData;
            res: {
                /**
                 * Successful Response
                 */
                202: TaskOutput;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/v1/list_videos': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<VideoInfo>;
            };
        };
    };
    '/health': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: number;
            };
        };
    };
};