// This file is auto-generated by @hey-api/openapi-ts

export type Body_process_video_file_v1_process_video_file_post = {
    file: (Blob | File);
    description: string;
    title: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type TaskOutput = {
    task_id: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type VideoRepr = {
    id: number;
    status: string;
    title: string;
    description: string | null;
    url: string | null;
    file_path: string | null;
    tags: string | null;
    video_path: string | null;
    text: string | null;
    audio_path: string | null;
};

export type VideoUrlInput = {
    video_url: string;
};

export type ProcessVideoUrlV1ProcessVideoUrlPostData = {
    requestBody: VideoUrlInput;
};

export type ProcessVideoUrlV1ProcessVideoUrlPostResponse = TaskOutput;

export type ProcessVideoFileV1ProcessVideoFilePostData = {
    formData: Body_process_video_file_v1_process_video_file_post;
};

export type ProcessVideoFileV1ProcessVideoFilePostResponse = TaskOutput;

export type GetVideoByIdV1VideosIdGetData = {
    id: unknown;
};

export type GetVideoByIdV1VideosIdGetResponse = VideoRepr;

export type GetVideosV1VideosGetData = {
    size?: unknown;
    skip?: unknown;
};

export type GetVideosV1VideosGetResponse = Array<VideoRepr>;

export type HealthHealthGetResponse = number;

export type $OpenApiTs = {
    '/v1/process_video_url': {
        post: {
            req: ProcessVideoUrlV1ProcessVideoUrlPostData;
            res: {
                /**
                 * Successful Response
                 */
                202: TaskOutput;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/v1/process_video_file': {
        post: {
            req: ProcessVideoFileV1ProcessVideoFilePostData;
            res: {
                /**
                 * Successful Response
                 */
                202: TaskOutput;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/v1/videos/{id}': {
        get: {
            req: GetVideoByIdV1VideosIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: VideoRepr;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/v1/videos': {
        get: {
            req: GetVideosV1VideosGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<VideoRepr>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/health': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: number;
            };
        };
    };
};